//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDeskApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookings
    {
        public int customerID { get; set; }
        public int roomID { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public string note { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual rooms rooms { get; set; }
    }
}
