//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        public int serviceID { get; set; }
        public string serviceType { get; set; }
        public Nullable<int> roomID { get; set; }
        public string serviceStatus { get; set; }
        public string note { get; set; }
    
        public virtual rooms rooms { get; set; }
    }
}
